language: node_js
node_js: '0.10'
# addons:
#   sauce_connect: true
branches:
  only:
  - master
env:
  global:
  - secure: orh/qjGCOk8zzATI19BV/qoV9Zv+m6C2sLeCYR1aeWXU2g9xX+f0iW960zrg1ja2Dj1PsX7c0SXbdXSUEko/AqQQqyiZZjE0r4SVZKn6fIBIGrZvnhkKwr7CtGdxWqy4PFNZi6DHLd6DKi2bFOUgmulk8GnZ64d2TstD9tEzLzA=
  - secure: iBYDR5myuv+J2NvdWfwlHE36JAFFduEoHSs91WRbnehwkd3AO89rSro0izeTbRM+e8VGGtNMr04RQTrcuu0mRSsrL+NOkACBWa42Z/EdE0ZAgAZdwz65gM+Ng9wXNhKZHEqN8pyGsNUA0RKyUoYcjOLkBoKeS/vUTqCb5aZDEyI=

before_script:
- npm install
- '`npm bin`/bower install'
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- '`npm bin`/webdriver-manager update --chrome'

script:
- 'node_modules/karma/bin/karma start  --single-run'
- './devserver.sh &'
- '`npm bin`/webdriver-manager start &'
- 'until $(wget -O /dev/null http://127.0.0.1:4444/wd/hub/); do sleep 1; done'
- '`npm bin`/protractor test/protractor.conf.js'
