# .travis.yml
branches:
  only:
    - master

before_script:
  - echo "hello world!"
  - npm install
  - "`npm bin`/bower install"
  - node server.js &
  - phantomjs --webdriver=4444 &

script: "`npm bin`/grunt build && `npm bin`/grunt test:e2e"
