# .travis.yml

branches:
  only:
    - master

before_script:
  - npm install > /dev/null
  - "`npm bin`/bower install > /dev/null"
  - node server.js &
  - phantomjs --webdriver=4444 &

script:
  - "`npm bin`/grunt build"
  - "`npm bin`/grunt clean:e2e coffee:e2e"
  - "`npm bin`/protractor test/build/e2e/conf.js"
  - "`npm bin`/karma start test/karma.conf.js --single-run"
