# .travis.yml

branches:
  only:
    - master

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - npm install
  - "`npm bin`/webdriver-manager update"
  - "`npm bin`/bower install"
  - node server.js &

script:
  - "`npm bin`/grunt build"
  - "`npm bin`/grunt test:e2e:chrome"
  - "`npm bin`/grunt test:e2e:firefox"
  - "`npm bin`/grunt test:e2e:phantomjs"
  - "`npm bin`/karma start test/karma.conf.js --single-run"
