# .travis.yml

branches:
  only:
    - master

before_install:
  - "Xvfb -fp /usr/share/fonts/X11/misc/ :22 -screen 0 1024x768x16 2>&1 &"
  - "export DISPLAY=:99.0"
  - "echo 1 || sh -e /etc/init.d/xvfb start"

before_script:
  - npm install
  - "`npm bin`/webdriver-manager update"
  - "`npm bin`/bower install"
  - node server.js &

script:
  - "`npm bin`/grunt build"
  - "`npm bin`/grunt test:e2e:firefox"
  - "echo 1 || `npm bin`/grunt test:e2e:chrome"
  - "echo 1 || `npm bin`/grunt test:e2e:phantomjs"
  - "`npm bin`/karma start test/karma.conf.js --single-run"
