# .travis.yml
branches:
  only:
    - master

before_script:
  - echo "hello world!"
  - npm install
  - bower install
  - node server.js &
  - phantomjs --webdriver=4444 &

script: "`npm bin`/grunt test:e2e"
